server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: ${DB_USERNAME:microservice_user}
#    password:
    password: shahryar
    driver-class-name: org.postgresql.Driver